name: Deploy to EC2 (QA)

on:
  push:
    branches:
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Deploy to EC2 (QA instance)
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.QA_HOST_DNS }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        TARGET: ${{ secrets.QA_TARGET_DIR }}

    - name: Executing remote ssh commands for QA
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.QA_HOST_DNS }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pm2 delete my-app || echo "No existing process found"
          cd ${{ secrets.QA_TARGET_DIR }}
          sudo git pull origin QA
          cd devops-aws
          sudo npm install
          sudo npm run build
          sudo pm2 start npm --name "my-app-qa" -- run dev
          sudo pm2 save
          echo "Application is running on QA environment."
